regla1: main.o Clase.o DtClase.o DtEntrenamiento.o DtSocio.o DtSpinning.o Entrenamiento.o Fecha.o Inscripcion.o Socio.o Spinning.o
	g++ main.o Clase.o DtClase.o DtEntrenamiento.o DtSocio.o DtSpinning.o Entrenamiento.o Fecha.o Inscripcion.o Socio.o Spinning.o

main.o: main.cpp

Clase.o: Clase.cpp

DtClase.o: DtClase.cpp

DtEntrenamiento.o: DtEntrenamiento.cpp

DtSocio.o: DtSocio.cpp

DtSpinning.o: DtSpinning.cpp

Entrenamiento.o: Entrenamiento.cpp

Fecha.o: Fecha.cpp

Inscripcion.o: Inscripcion.cpp

Socio.o: Socio.cpp

Spinning.o: Spinning.cpp
