regla1: Fecha.o DtSocio.o Socio.o Inscripcion.o DtClase.o Clase.o DtEntrenamiento.o DtSpinning.o Entrenamiento.o Spinning.o main.o 
	g++ -I./include/ -Wall -o programa Fecha.o DtSocio.o Socio.o Inscripcion.o DtClase.o Clase.o DtEntrenamiento.o DtSpinning.o Entrenamiento.o Spinning.o main.o

Fecha.o: src/Fecha.cpp
	g++ -I./include/ -Wall -c src/Fecha.cpp -o Fecha.o

DtSocio.o: src/DtSocio.cpp
	g++ -I./include/ -Wall -c src/DtSocio.cpp -o DtSocio.o

Socio.o: src/Socio.cpp
	g++ -I./include/ -Wall -c src/Socio.cpp -o Socio.o

Inscripcion.o: src/Inscripcion.cpp
	g++ -I./include/ -Wall -c src/Inscripcion.cpp -o Inscripcion.o

DtClase.o: src/DtClase.cpp
	g++ -I./include/ -Wall -c src/DtClase.cpp -o DtClase.o

Clase.o: src/Clase.cpp
	g++ -I./include/ -Wall -c src/Clase.cpp -o Clase.o

DtEntrenamiento.o: src/DtEntrenamiento.cpp
	g++ -I./include/ -Wall -c src/DtEntrenamiento.cpp -o DtEntrenamiento.o

DtSpinning.o: src/DtSpinning.cpp
	g++ -I./include/ -Wall -c src/DtSpinning.cpp -o DtSpinning.o

Entrenamiento.o: src/Entrenamiento.cpp
	g++ -I./include/ -Wall -c src/Entrenamiento.cpp -o Entrenamiento.o

Spinning.o: src/Spinning.cpp
	g++ -I./include/ -Wall -c src/Spinning.cpp -o Spinning.o

main.o: main.cpp
	g++ -I./include/ -Wall -c main.cpp -o main.o
